
services:
  dns_sync:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./data/:/app/data/
      - ./sql_app.db:/app/sql_app.db
    environment:
      SQLALCHEMY_DATABASE_URL: "sqlite:///./data/sqlite.db"
      BACKUP_FILE: './data/backup.json'
      DOMAIN_CONFIG: '{"example.com": {"zone_id": "my_zone_id", "jwt": "${my_bearer}"}}'
