
services:
  dns_sync:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./backup/:/app/backup/
      - ./sql_app.db:/app/sql_app.db
    environment:
      DOMAIN_CONFIG: '{"example.com": {"zone_id": "my_zone_id", "jwt": "${my_bearer}"}}'
volumes:
  backup:
  sql_app.db:
