[tool.black]
line-length = 88
target-version = ['py38']
skip-string-normalization = true
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
env_files = [
    ".test.env"
]

[tool.mypy]
plugins = "sqlalchemy.ext.mypy.plugin"
